steps:
# Dockerイメージの作成
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/TEMP_GitHub_Actions:$COMMIT_SHA', '.']
# DockerイメージをContainer RegistryへPush
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/TEMP_GitHub_Actions:$COMMIT_SHA']
# DockerイメージをClourd Runへデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'TEMP_GitHub_Actions'
  - '--image'
  - 'gcr.io/$PROJECT_ID/TEMP_GitHub_Actions:$COMMIT_SHA'
  - '--region'
  - 'us-west1'
images:
- 'gcr.io/$PROJECT_ID/TEMP_GitHub_Actions:$COMMIT_SHA'