version: '3'
services:
  # 名前
  gpr-app:
    # build・・・dockerフォルダのDockerfileからイメージを構築します。
    build:
      context: .   # 必要っぽい
      dockerfile: ./docker/Dockerfile
    volumes:
      # volumes・・・ホスト側のフォルダと、コンテナ内のフォルダをマウントします。
      # Docker Compose には独自のプロジェクトの概念があり、デフォルトではymlが置かれたカレントディレクトリがプロジェクト名とされる
      # 現在のディレクトリをマウントします。もしかしたら僕のやりたいことはできなくて、compose ファイルは最上位のディレクトリに置いてマウントしないといけないのかもしれない
      - .:/home/projects:cached
    ports:
      # - "4200:4200"  # ホストマシンのポート4200を、docker内のポート4200に接続する
      - 4200:4200  # どっちの書き方でも大丈夫っぽい
    environment:
      # environmentのCHOKIDAR_USEPOLLING=true・・・ホットリロード（プログラムの変更を瞬時にUIに反映する機能）を有効にするために記述します。
      - CHOKIDAR_USEPOLLING=true
      # tty・・・runコマンドの-tオプションと同じで、疑似端末（カーソルの移動や文字の入力などを行う端末）を割り当てます。
    tty: true
    # stdin_open・・・runコマンドの-iオプションと同じで、標準入出力をコンテナに割り当てます。
    stdin_open: true