name: Action Sample

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # ５分ごと
  workflow_dispatch:

jobs:
  python-Sample:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: 'x64'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python
        run: python temp_make_regression.py