name: Action Sample

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/5 * * * *' # ５分ごと
  workflow_dispatch:

jobs:
  python-Sample:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: 'x64'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python
        # Settingsを扱えるのは、リポジトリのオーナーのみ
        # run内に書いたスクリプトでsecretが扱えるようになる
        # https://qiita.com/developer-kikikaikai/items/60b209c065f076dca7a1
        env:
          project_id: ${{ secrets.GCP_PROJECT_ID }}         # GCPのプロジェクトID
          service_account_key: ${{ secrets.GCP_SA_KEY }}    # GCPのサービスアカウント
        run: |
            echo $service_account_key | base64 --decode > credential.json   # base64 のデータをデコードしてクレデンシャル情報を復元する(https://soypocket.com/it/github-actions-json-secrets/)
            python make_regression.py

      - name: CSV commit
        run: |
            git config --global user.email ${{secrets.EMAIL}}
            git config --global user.name ${{secrets.NAME}}
            git add -A
            git commit -m "add CSV"
            git push origin main