name: First Training Model

on:
  push:
    branches:
      - main
  # Github Actionsワークフローをコードレベルで起動するには、workflow_dispatchトリガーを使用する必要がある
  workflow_dispatch:

# Settingsを扱えるのは、リポジトリのオーナーのみ
# run内に書いたスクリプトでsecretが扱えるようになる
# https://qiita.com/developer-kikikaikai/items/60b209c065f076dca7a1
env:
  project_id: ${{ secrets.GCP_PROJECT_ID }}         # GCPのプロジェクトID
  service_account_key: ${{ secrets.GCP_SA_KEY }}    # GCPのサービスアカウント

jobs:
  First-Training-Model:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
          architecture: 'x64'

      # zsh を入れようとするとエラーになるので入れない
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r etc/requirements.txt

      - name: Run Python make_regression_data
        run: |
            echo $service_account_key | base64 --decode > ./credential.json   # base64 のデータをデコードしてクレデンシャル情報を復元する(https://soypocket.com/it/github-actions-json-secrets/)
            export GOOGLE_APPLICATION_CREDENTIALS="./credential.json"         # デコードしたクレデンシャル情報をセットする
            python src/make_data/make_regression.py                           # スクリプト実行

      - name: Run Python complement_missing_value_data
        run: |
            sleep 5s                                                          # 5秒後に実行する(なんとなくバッファを入れた)
            export GOOGLE_APPLICATION_CREDENTIALS="./credential.json"         # 同じ処理をしないといけない。もっと良いやり方はありそう
            python src/make_data/missing_value_completion.py                  # スクリプト実行

      # 初回はこれを実行してモデルを保存する。モデルの保存が行われるので Cloud Build が発火する
      # 次に：データが GCS にアップロードされているはずなので Airbyte を手動で1回だけ実行させる → BigQuery にデータがインサートされる
      # 10分後に Airbyte で「24時間ごとに起動する設定」を Enable に設定する
      - name: Run Python GaussianProcessRegressor_first_training
        env:
          ON_RETRAIN_MODE: False
        run: |
            sleep 3m                                                          # Airbyte を起動させている間の待機時間を3mで設定する
            export GOOGLE_APPLICATION_CREDENTIALS="./credential.json"         # 同じ処理をしないといけない。もっと良いやり方はありそう
            python src/ml/training.py                                         # スクリプト実行
            rm credential.json                                                # 間違ってPUSHしないようにクレデンシャルファイルは削除する

      - name: First Training commit
        run: |
            git config --global user.email ${{secrets.EMAIL}}
            git config --global user.name ${{secrets.NAME}}
            git add -A
            git commit -m "add First Training Files"
            git push origin main